version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    restart: unless-stopped
    image: mysql:5.7
    build:
      context: .
    env_file: .env
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - ${MYSQL_DOCKER_PORT}:${MYSQL_DOCKER_PORT}
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - custom-network
  app:
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_DATASOURCE_URL: "${MYSQL_URL}:${MYSQL_DOCKER_PORT}/${MYSQL_DATABASE}?useSSL=false"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb
    networks:
      - custom-network

volumes:
  mysqldb:
    driver: local

networks:
  custom-network:
    driver: bridge